### PR TITLE
Adding a block for running code in the game engine update logic

### PR DESCRIPTION
**Pull request by riknoll**
Feel free to ignore if this doesn't seem useful, but I thought this might be a nice addition. Lets you run code before/after a specific step in the game engine update logic

Screen Shot 2021-05-11 at 10 58 39 AM

### CODE REVIEW

**Review by jwunderl — APPROVED** [review]
ooo this is a great advanced block yes! 

in case it's useful / since I had to check anyways, the frame handler orders just compare as numbers here https://github.com/microsoft/pxt-common-packages/blob/master/libs/base/eventcontext.ts#L154 so decimals are valid, which is good to know

**Comment by jwunderl** [comment]
Oh, could you add the docs page to the pxt.json files and then I'll merge it / bump?

**Comment by riknoll** [comment]
done!

**Comment by jwunderl** [comment]
Bumped, it's in v0.2.0~

**Pull request merged**
